// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdyamdpfzywbkahidwcm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkeWFtZHBmenl3YmthaGlkd2NtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1NDk2MjgsImV4cCI6MjA3NDEyNTYyOH0.hr9113R6R_MoYNDHZhdpNCU90q0x0hOjhmCtofxm0gQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});